# Generated by Django 4.1.2 on 2022-10-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_remove_recipt_total_alter_discount_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipt',
            name='discount',
        ),
        migrations.AddField(
            model_name='recipt',
            name='discount',
            field=models.ManyToManyField(to='checkout.discount'),
        ),
    ]
